# Site settings
title: shinde.co *folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  Harshal Shinde | Architect, Interior Designer & Furniture-maker at URBAN ARTS | Architecture, Interior & Furniture Design, Urban Design & Conservation
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: harshalshinde
github_username:  hpshinde

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  words:
    output: true
    permalink: /poetry/:path/
  images:
    output: true
    permalink: /images/:path/


